apiVersion: v1
kind: Service
metadata:
  name: elgoog-drive-backend-service
  namespace: elgoog
spec:
  selector:
    app: elgoog-drive-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP