apiVersion: v1
kind: Service
metadata:
  name: elgoog-drive-frontend-service
  namespace: elgoog
spec:
  selector:
    app: elgoog-drive-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer